### ISSUE TITLE
Change Any::Moose for Moo

### ISSUE THREAD

**Issue by joenio** [evalEmpire/method-signatures#117] opened 2015-06-03 13:35 UTC
Any::Mooses's documentation warns about DEPRECATION.

Does it make any sense use Moo instead of Any::Moose?

**Comment by barefootcoder** [comment] 2015-06-17 03:11
> Does it make any sense use Moo instead of Any::Moose?

This is an issue which has been brought up many times ... mainly in [RT/88716](https://rt.cpan.org/Public/Bug/Display.html?id=88716).  You could also look at the discussions in #81, #85, and lately even #116.  Since this discussion is a duplicate of one or more of those, I'm going to go ahead and close this one.  But please don't hesitate to comment in one of those other places if you feel they don't asnwer your questions sufficiently.

Thx for your interest.

**Closed by barefootcoder** 2015-06-17 03:11 UTC

**Comment by nicklangridge** [comment] 2019-08-03 08:43
Is Method::Signatures still being maintained? I also came here to report the Any::Moose deprecation issue but looks like it's a lost cause?

**Comment by barefootcoder** [comment] 2019-09-04 00:14
> Is Method::Signatures still being maintained?

Well, I try to keep an eye open for serious bugs, but I'll admit no one has put much development work into MSig lately.  The issue is, we use `Devel::Declare` here, and that's _seriously_ out of favor these days.  As long as you can use at least 5.14 or so, you have access to the keyword API and solutions like `Kavorka` are going to be mostly superior.  (I have some personal bugaboos with Kavorka, but I still think MSig would be well served by one day becoming a wrapper around it and just tweaking some of its defaults.  I actually tried a couple of times, but ran into some non-trivial issues.  But that's more of a discussion for #116.)

> I also came here to report the Any::Moose deprecation issue but looks like it's a lost cause?

Not at all.  If you check the discussion in #81 (which I reference earlier in this issue), you'll see what the hold-up is: we need unit tests.  Nothing has changed since I wrote that other than the passage of time.  (Side note: #81 is still an open issue.  This one is closed.)

> For context, I wrote a command line utility which uses Method::Signatures but each run of the command displays the deprecation warning. I can't see a way to suppress it except to do something nasty (like monkey-patch Any::Moose).

Well, my personal approach for that is just to use the next-to-last version of `Any::Moose`.  (Note that 0.26 and 0.27 are _identical_, other than 0.27 having the deprecation warning.)  In a `cpanfile`, that's as simple as:

    requires 'Any::Moose', '== 0.26';

Just on the command-line, something like `cpanm Any::Moose@0.26` should work.

Is this cheating a bit?  Sure.  But it's not, as you say, something nasty like monkey-patching, and so far it's been trivial enough to do that it's kept me from being forced to sink the hours into developing the unit tests.  Perhaps it could help in your case as well.

**Comment by nicklangridge** [comment] 2019-09-04 09:32
Thanks for taking the time to respond.

I've read through #81 so have a better understanding of the situation now - unfortunately I'm not in a position to help out with unit tests myself.

The work around you suggest sounds reasonable - I'll go with that.
